# Note: HTTPS via CloudFlare. Pretty silly for a little project like this but
# wanted to get my hands dirty with it.
baseURL = "https://shipped.software"
languageCode = "en-us"
title = "Shipped ðŸ“¦"
theme = "anybodyhome"

MetaDataFormat = "yaml"

[params]
  subtitle = "A blog about shipping software"
